/* ===== Motivational Quotes & Jump Principles — 3 Languages ===== */
/* Sources: NotebookLM (Athletic Performance & Biomechanics), Web Research */

const MOTIVATION_QUOTES = [
    // ── Coaches & Trainers ──
    { en: "Never plan to be 1st. Plan to be better.", ru: "Не планируй быть первым. Планируй стать лучше.", cn: "不要计划成为第一。要计划变得更好。", author: "Bryan Roy" },
    { en: "If you don't try to be the best, then why should your athletes?", ru: "Если ты не стараешься быть лучшим — зачем это твоим спортсменам?", cn: "如果你不努力做到最好，你的运动员为什么要？", author: "Bryan Roy" },
    { en: "Hide nothing. Share everything.", ru: "Ничего не скрывай. Делись всем.", cn: "不要隐藏任何东西。分享一切。", author: "Bryan Roy" },
    { en: "Success in the high jump is usually the result of superior execution, not greater effort.", ru: "Успех в прыжках в высоту — результат превосходного исполнения, а не большего усилия.", cn: "跳高的成功通常源于卓越的执行力，而非更大的努力。", author: "Bozeman Track & Field" },
    { en: "Just doing something and repeating it a hundred times means nothing. In the end it's quality that counts.", ru: "Просто делать что-то и повторять сто раз — ничего не значит. В конце концов считается качество.", cn: "仅仅重复做某事一百次毫无意义。最终重要的是质量。", author: "Wolfgang Ritzdorf" },
    { en: "Strength and power have no value by themselves — they matter only as support for reactive strength.", ru: "Сила и мощность не имеют ценности сами по себе — они важны лишь как поддержка реактивной силы.", cn: "力量和爆发力本身没有价值——它们仅作为反应力的支撑才重要。", author: "Wolfgang Ritzdorf" },
    { en: "All successful jumps show these elements and there is no alternative to getting them right!", ru: "Все успешные прыжки содержат эти элементы, и нет альтернативы тому, чтобы выполнить их правильно!", cn: "所有成功的跳跃都包含这些要素，正确执行它们没有替代方案！", author: "Wolfgang Ritzdorf" },
    { en: "In the high jump, nearly all faults can be traced back to the approach.", ru: "В прыжках в высоту почти все ошибки можно проследить до разбега.", cn: "在跳高中，几乎所有错误都可以追溯到助跑。", author: "Boo Schexnayder" },
    { en: "One jump, one cue. Giving three or more instructions often results in paralysis of analysis.", ru: "Один прыжок — одна подсказка. Три и более инструкции ведут к параличу анализа.", cn: "一次跳跃，一个提示。给出三个以上的指令往往导致分析瘫痪。", author: "Matt Burns" },
    { en: "Progress comes from concentrating on the process of training, not on the outcome.", ru: "Прогресс приходит от сосредоточенности на процессе тренировки, а не на результате.", cn: "进步来自于专注训练过程，而非结果。", author: "Bozeman Track & Field" },
    { en: "Coach consistency. Without it, most of your athletes' training is simply wasted.", ru: "Тренируй стабильность. Без неё большая часть тренировок твоих спортсменов просто впустую.", cn: "指导一致性。没有它，你运动员的大部分训练都是白费的。", author: "Bozeman Track & Field" },
    { en: "Don't desensitize early! If you throw out all your top-shelf training means early, they'll be less effective later.", ru: "Не десенсибилизируй рано! Если выбросишь все лучшие средства в начале — потом они будут менее эффективны.", cn: "不要过早脱敏！如果你过早使用所有顶级训练手段，后期效果会下降。", author: "Joel Smith" },
    { en: "Build hamstrings that fire better, not just get bigger.", ru: "Развивай бицепсы бедра, которые лучше включаются, а не просто становятся больше.", cn: "培养响应更好的腘绳肌，而不仅仅是更大的。", author: "Joel Smith" },
    { en: "Force absorption over force production.", ru: "Поглощение силы важнее производства силы.", cn: "力的吸收比力的产生更重要。", author: "Bob Thurnhoffer" },
    { en: "Training must progress to the point where it makes competition easier.", ru: "Тренировка должна дойти до той точки, где она делает соревнование легче.", cn: "训练必须进步到使比赛变得更容易的程度。", author: "Bob Thurnhoffer" },
    { en: "Keep neural days neural, general days general.", ru: "Держи нервные дни нервными, общие дни — общими.", cn: "保持神经训练日专注神经训练，一般训练日做一般训练。", author: "Bob Thurnhoffer" },
    { en: "Imagine that the ground is hot lava.", ru: "Представь, что земля — это горячая лава.", cn: "想象地面是滚烫的岩浆。", author: "Plyometric Cue" },
    { en: "Winning mindsets come from consistent habits.", ru: "Победный менталитет рождается из постоянных привычек.", cn: "胜利的心态来自于持续的习惯。", author: "Dr. Paul McCarthy" },
    { en: "Develop a process for your athletes to use. Over-explain. Be predictable.", ru: "Разработай процесс для спортсменов. Объясняй подробно. Будь предсказуемым.", cn: "为你的运动员制定一个流程。详细解释。保持可预测性。", author: "Bill Richardson" },
    { en: "If we keep doing things the same way, then track will never change.", ru: "Если мы продолжим делать всё по-старому, лёгкая атлетика никогда не изменится.", cn: "如果我们继续以同样的方式做事，田径永远不会改变。", author: "Adarian Barr" },

    // ── Famous Athletes ──
    { en: "There is technology now, there is support now. All you need is discipline.", ru: "Сейчас есть технологии, есть поддержка. Всё, что тебе нужно — это дисциплина.", cn: "现在有技术，有支持。你所需要的只是纪律。", author: "Javier Sotomayor" },
    { en: "Patience is key. Any athlete will face injuries and setbacks — stay patient no matter what.", ru: "Терпение — ключ. Любой спортсмен столкнётся с травмами и неудачами — будь терпелив, что бы ни случилось.", cn: "耐心是关键。任何运动员都会面临伤病和挫折——无论如何都要保持耐心。", author: "Mutaz Essa Barshim" },
    { en: "Smart work, not hard work. Training is not necessarily about hard work, but smart work.", ru: "Умная работа, а не тяжёлая. Тренировки — это не обязательно тяжёлый труд, а умный труд.", cn: "聪明地训练，而非拼命训练。训练不一定是艰苦的，而是聪明的。", author: "Mutaz Essa Barshim" },
    { en: "Most athletes train physically, but it is also important to link mind and body to prepare mentally.", ru: "Большинство спортсменов тренируются физически, но важно также связать разум и тело для ментальной подготовки.", cn: "大多数运动员进行体能训练，但将身心联系起来进行心理准备同样重要。", author: "Mutaz Essa Barshim" },
    { en: "High jump is my passion. I want to make sure my name is mentioned whenever high jump is mentioned.", ru: "Прыжки в высоту — моя страсть. Я хочу, чтобы моё имя звучало всякий раз, когда говорят о прыжках в высоту.", cn: "跳高是我的热情。我希望每当提到跳高时都能提到我的名字。", author: "Mutaz Essa Barshim" },
    { en: "If you love something, do everything you can. It may seem impossible, it may seem difficult — if you truly believe in yourself, it's worth it.", ru: "Если ты любишь что-то — делай всё возможное. Может казаться невозможным, может быть трудным — если веришь в себя, оно того стоит.", cn: "如果你热爱某件事，就尽一切努力。可能看起来不可能，可能很困难——如果你真正相信自己，那就值得。", author: "Mutaz Essa Barshim" },
    { en: "High jump is like a puzzle — it requires a blend of speed, flexibility, and strength. There's always something to improve.", ru: "Прыжок в высоту — как пазл: нужно сочетание скорости, гибкости и силы. Всегда есть что улучшить.", cn: "跳高就像拼图——需要速度、柔韧性和力量的结合。总有可以改进的地方。", author: "Mutaz Essa Barshim" },
    { en: "I believe the flop was a natural style and I was just the first to find it.", ru: "Я верю, что флоп был естественным стилем, и я просто первым его нашёл.", cn: "我相信背越式是一种自然的风格，我只是第一个发现它的人。", author: "Dick Fosbury" },
    { en: "All I could do was shrug my shoulders and say: this is what I do. Let's go see what happens.", ru: "Всё, что я мог — пожать плечами и сказать: это то, что я делаю. Пойдём посмотрим, что будет.", cn: "我能做的就是耸耸肩说：这就是我做的。让我们去看看会发生什么。", author: "Dick Fosbury" },
    { en: "I knew that my technique was my path to success.", ru: "Я знал, что моя техника — это мой путь к успеху.", cn: "我知道我的技术是我通往成功的道路。", author: "Dick Fosbury" },
    { en: "Worrying gets you nowhere. Train hard, turn up, run your best and the rest will take care of itself.", ru: "Беспокойство ни к чему не ведёт. Тренируйся упорно, приходи, выкладывайся по максимуму — остальное сложится само.", cn: "担心无济于事。刻苦训练，全力以赴——其余的自然会水到渠成。", author: "Usain Bolt" },
    { en: "Easy is not an option. No days off. Never quit. Be fearless.", ru: "Лёгкий путь — не вариант. Без выходных. Никогда не сдавайся. Будь бесстрашным.", cn: "轻松不是选项。没有休息日。永不放弃。无所畏惧。", author: "Usain Bolt" },
    { en: "Talent you have naturally. Skill is only developed by hours and hours of work.", ru: "Талант дан от природы. Мастерство развивается только часами и часами работы.", cn: "天赋是与生俱来的。技能只能通过无数小时的努力来培养。", author: "Usain Bolt" },
    { en: "I trained 4 years to run 9 seconds and people give up when they don't see results in 2 months.", ru: "Я тренировался 4 года, чтобы пробежать 9 секунд, а люди сдаются, не видя результатов за 2 месяца.", cn: "我训练了4年才跑出9秒的成绩，而人们2个月看不到结果就放弃了。", author: "Usain Bolt" },
    { en: "I don't think limits.", ru: "Я не думаю о пределах.", cn: "我不考虑极限。", author: "Usain Bolt" },
    { en: "If you don't have confidence, you'll always find a way not to win.", ru: "Если у тебя нет уверенности, ты всегда найдёшь способ не выиграть.", cn: "如果你没有自信，你总会找到不赢的方式。", author: "Carl Lewis" },
    { en: "Scientists have proven that it's impossible to long-jump 30 feet, but I don't listen to that kind of talk. Thoughts like that have a way of sinking into your feet.", ru: "Учёные доказали, что невозможно прыгнуть в длину 30 футов, но я не слушаю такие разговоры. Такие мысли имеют свойство проникать в ноги.", cn: "科学家已经证明不可能跳远30英尺，但我不听这种话。这种想法会渗入你的双脚。", author: "Carl Lewis" },
    { en: "Channel your energy. Focus.", ru: "Направляй энергию. Фокусируйся.", cn: "集中你的能量。专注。", author: "Carl Lewis" },
    { en: "Champions are built in training, far from the spotlight.", ru: "Чемпионы создаются на тренировках, далеко от прожекторов.", cn: "冠军在训练中铸就，远离聚光灯。", author: "Carl Lewis" },
    { en: "I let my feet spend as little time on the ground as possible. From the air, fast down — and from the ground, fast up.", ru: "Я стараюсь, чтобы ноги проводили как можно меньше времени на земле. С воздуха быстро вниз — и с земли быстро вверх.", cn: "我让双脚在地面上停留的时间尽可能短。从空中迅速下落——从地面迅速起跳。", author: "Jesse Owens" },
    { en: "A lifetime of training for just ten seconds.", ru: "Целая жизнь тренировок ради десяти секунд.", cn: "一生的训练只为十秒钟。", author: "Jesse Owens" },
    { en: "I've failed over and over and over again in my life. And that is why I succeed.", ru: "Я терпел неудачу снова, снова и снова в жизни. И именно поэтому я добился успеха.", cn: "我一次又一次地失败。这就是我成功的原因。", author: "Michael Jordan" },
    { en: "I can accept failure, everyone fails at something. But I can't accept not trying.", ru: "Я могу принять поражение — каждый в чём-то проигрывает. Но я не могу принять отказ от попытки.", cn: "我可以接受失败，每个人都会在某些事上失败。但我无法接受不去尝试。", author: "Michael Jordan" },
    { en: "Obstacles don't have to stop you. If you run into a wall, figure out how to climb it, go through it, or work around it.", ru: "Препятствия не обязаны тебя останавливать. Если наткнулся на стену — найди способ перелезть, пройти сквозь или обойти.", cn: "障碍不必阻止你。如果你遇到了墙，想办法翻过去、穿过去或绕过去。", author: "Michael Jordan" },
    { en: "The minute you get away from fundamentals, the bottom can fall out of your game.", ru: "Как только ты отклоняешься от основ — всё может рухнуть.", cn: "一旦你脱离基本功，你的表现就可能崩塌。", author: "Michael Jordan" },
    { en: "You can't get much done in life if you only work on the days when you feel good.", ru: "Мало чего добьёшься, если работаешь только в дни, когда чувствуешь себя хорошо.", cn: "如果你只在感觉良好的日子才工作，你不会取得太多成就。", author: "Michael Jordan" },
    { en: "It's the brain, not the heart or lungs, that's the critical organ.", ru: "Мозг, а не сердце или лёгкие — вот критический орган.", cn: "关键器官是大脑，而不是心脏或肺。", author: "Sir Roger Bannister" },
    { en: "The more I train, the more I realize it's not about the medals. It's about the journey and the person I become.", ru: "Чем больше я тренируюсь, тем больше понимаю: дело не в медалях, а в пути и в том, кем я становлюсь.", cn: "我训练得越多，就越意识到这不是关于奖牌，而是关于旅程和我成为的那个人。", author: "Allyson Felix" },
    { en: "The will to win means nothing without the will to prepare.", ru: "Воля к победе ничего не значит без воли к подготовке.", cn: "没有准备的意志，赢的意志毫无意义。", author: "Juma Ikangaa" },
    { en: "To be number one, you have to train like you're number two.", ru: "Чтобы быть номером один, нужно тренироваться как номер два.", cn: "要成为第一，你必须像第二名一样训练。", author: "Maurice Greene" },
    { en: "Somewhere in the world someone is training when you are not. When you race him, he will win.", ru: "Где-то в мире кто-то тренируется, когда ты отдыхаешь. Когда ты побежишь с ним — он победит.", cn: "世界上某个地方有人在你不训练的时候训练。当你和他比赛时，他会赢。", author: "Tom Fleming" },
    { en: "I always felt that my greatest asset was not my physical ability — it was my mental ability.", ru: "Я всегда чувствовал, что мой главный актив — не физические способности, а умственные.", cn: "我一直觉得我最大的资本不是身体能力，而是心理能力。", author: "Bruce Jenner" },

    // ── Scientists & Researchers ──
    { en: "Nature has provided man with the possibility to enhance his abilities in extreme situations — we need to utilize it.", ru: "Природа дала человеку возможность усиливать свои способности в экстремальных ситуациях — нужно это использовать.", cn: "大自然赋予了人类在极端情况下增强能力的可能性——我们需要利用它。", author: "Yuri Verkhoshansky" },
    { en: "The body mobilizes any innate mechanisms designed by nature to be available for extreme situations.", ru: "Тело мобилизует все врождённые механизмы, предусмотренные природой для экстремальных ситуаций.", cn: "身体会动员大自然为极端情况设计的所有先天机制。", author: "Yuri Verkhoshansky" },
    { en: "Life is trying things to see if they work. Creativity is just connecting things.", ru: "Жизнь — это попытки, чтобы увидеть, что работает. Творчество — это просто соединение вещей.", cn: "生活就是尝试，看看什么有效。创造力只是将事物联系起来。", author: "Natalia Verkhoshansky" },
    { en: "Being a creative coach means trying new training methods to see if they are effective.", ru: "Быть творческим тренером — значит пробовать новые методы, чтобы увидеть, эффективны ли они.", cn: "做一个有创造力的教练意味着尝试新的训练方法，看看它们是否有效。", author: "Natalia Verkhoshansky" },

    // ── Universal Wisdom ──
    { en: "Pressure is a privilege.", ru: "Давление — это привилегия.", cn: "压力是一种特权。", author: "Billie Jean King" },
    { en: "Full effort is full victory.", ru: "Полное усилие — полная победа.", cn: "全力以赴即是全面胜利。", author: "Mahatma Gandhi" },
    { en: "Whether you believe you can or believe you can't — you're right.", ru: "Веришь, что можешь, или веришь, что не можешь — в обоих случаях ты прав.", cn: "无论你相信你能还是不能——你都是对的。", author: "Henry Ford" },
    { en: "The body achieves what the mind believes.", ru: "Тело достигает того, во что верит разум.", cn: "身体能实现心灵所相信的。", author: "" },
    { en: "Mental toughness isn't about big championship moments — it's about winning small daily battles consistently.", ru: "Ментальная стойкость — это не о больших моментах чемпионатов, а о том, чтобы последовательно выигрывать маленькие ежедневные битвы.", cn: "心理韧性不在于重大锦标赛时刻——而在于持续赢得每天的小战斗。", author: "" },
    { en: "Pain is temporary, pride is forever.", ru: "Боль временна, гордость — навсегда.", cn: "痛苦是暂时的，骄傲是永恒的。", author: "" },
    { en: "If it doesn't challenge you, it doesn't change you.", ru: "Если это не бросает тебе вызов — это тебя не меняет.", cn: "如果没有挑战，就不会有改变。", author: "" },
    { en: "A champion is someone who gets up when they can't.", ru: "Чемпион — тот, кто встаёт, когда уже не может.", cn: "冠军是在无法站起来时依然站起来的人。", author: "" },
    { en: "In training, you listen to your body. In competition, you tell your body to shut up.", ru: "На тренировке ты слушаешь своё тело. На соревнованиях — приказываешь ему замолчать.", cn: "训练时你倾听身体。比赛时你让身体闭嘴。", author: "" },
    { en: "Don't dream of winning — train for it.", ru: "Не мечтай о победе — тренируйся для неё.", cn: "不要梦想胜利——为之训练。", author: "" },
    { en: "Run when you can, walk if you have to, crawl if you must — just never give up.", ru: "Беги, когда можешь, иди, если нужно, ползи, если надо — только не сдавайся.", cn: "能跑就跑，必须走就走，不得已就爬——只是永远不要放弃。", author: "" },
    { en: "Strength does not come from physical capacity. It comes from an indomitable will.", ru: "Сила не в физических возможностях. Она в несгибаемой воле.", cn: "力量不来自身体能力，而来自不屈的意志。", author: "" },
    { en: "No one can say 'You must not run faster than this, or jump higher than that.' The human spirit is indomitable.", ru: "Никто не может сказать: «Ты не должен бежать быстрее или прыгать выше этого». Человеческий дух непобедим.", cn: "没有人可以说'你不能跑得更快或跳得更高'。人类精神是不可征服的。", author: "" },
    { en: "Visualization activates the same neural pathways you use during physical execution — extra practice without physical strain.", ru: "Визуализация активирует те же нейронные пути, что и физическое выполнение — дополнительная практика без физической нагрузки.", cn: "可视化激活了与身体执行相同的神经通路——无需身体负担的额外练习。", author: "" },
    { en: "Continuous improvement is better than delayed perfection.", ru: "Постоянное улучшение лучше отложенного совершенства.", cn: "持续改进胜过延迟的完美。", author: "" },
    { en: "Success isn't given. It's earned on the track, on the field, in the gym — with blood, sweat, and tears.", ru: "Успех не дарят. Его зарабатывают на дорожке, на площадке, в зале — потом, кровью и слезами.", cn: "成功不是被给予的。它是在跑道上、赛场上、健身房里——用汗水、鲜血和泪水赢得的。", author: "" },
    { en: "Failure is not the opposite of success — it's part of success.", ru: "Провал — не противоположность успеха, а его часть.", cn: "失败不是成功的对立面——它是成功的一部分。", author: "" },
    { en: "Keep working even when no one is watching.", ru: "Продолжай работать, даже когда никто не смотрит.", cn: "即使没有人注目，也要继续努力。", author: "" },
    { en: "Set a goal that makes you want to jump out of bed in the morning.", ru: "Поставь цель, ради которой хочется выпрыгнуть из кровати утром.", cn: "设定一个让你早上想从床上跳起来的目标。", author: "" },
    { en: "Mental will is a muscle that needs exercise, just like muscles of the body.", ru: "Сила воли — мышца, которую нужно тренировать, как и мышцы тела.", cn: "意志力是一块需要锻炼的肌肉，就像身体的肌肉一样。", author: "" },
];

const JUMP_PRINCIPLES = [
    { en: "The approach is the most important aspect of high jumping — it places the takeoff foot in the exact same spot every time.", ru: "Разбег — важнейший аспект прыжка в высоту: он ставит толчковую ногу в одну и ту же точку каждый раз.", cn: "助跑是跳高最重要的方面——每次将起跳脚放在完全相同的位置。", icon: "🏃" },
    { en: "Vertical velocity at takeoff is the single most important factor determining the height cleared.", ru: "Вертикальная скорость при отталкивании — главный фактор, определяющий преодолённую высоту.", cn: "起跳时的垂直速度是决定跳过高度的最重要因素。", icon: "⬆️" },
    { en: "Reactive strength — the ability to quickly switch from eccentric to concentric contraction — is the key biomotor ability for jumpers.", ru: "Реактивная сила — способность быстро переключаться от эксцентрического к концентрическому сокращению — ключевая способность прыгуна.", cn: "反应力——从离心收缩快速转换为向心收缩的能力——是跳跃运动员的关键运动能力。", icon: "⚡" },
    { en: "The J-shaped curve approach generates centrifugal force that helps launch the athlete over the bar.", ru: "J-образный разбег создаёт центробежную силу, помогающую спортсмену перелететь через планку.", cn: "J形弯道助跑产生离心力，帮助运动员飞越横杆。", icon: "🔄" },
    { en: "The penultimate step is critical — it lowers the center of mass while minimizing speed loss for optimal vertical drive.", ru: "Предпоследний шаг критичен — он понижает центр масс при минимальной потере скорости для оптимального вертикального толчка.", cn: "倒数第二步至关重要——它降低质心同时最小化速度损失，实现最佳垂直推力。", icon: "👣" },
    { en: "Once airborne, the path of the center of mass is predetermined — it cannot be changed after leaving the ground.", ru: "В воздухе траектория центра масс предопределена — её нельзя изменить после отрыва от земли.", cn: "一旦腾空，质心轨迹就已确定——离地后无法改变。", icon: "🎯" },
    { en: "Vigorous upward arm action during push-off contributes significantly to the vertical velocity of the center of mass.", ru: "Энергичное движение руками вверх при толчке значительно увеличивает вертикальную скорость центра масс.", cn: "起跳时有力的上臂摆动显著提高质心的垂直速度。", icon: "💪" },
    { en: "Run-up should be at maximum controllable speed — too fast and you can't take off; too slow and you lose height.", ru: "Разбег должен быть на максимальной контролируемой скорости — слишком быстро — не оттолкнёшься; слишком медленно — потеряешь высоту.", cn: "助跑应以最大可控速度进行——太快无法起跳，太慢会失去高度。", icon: "⚖️" },
    { en: "Quality over quantity in plyometrics — high reps become jump training, not plyometric training.", ru: "Качество важнее количества в плиометрике — много повторений превращаются в прыжковую тренировку, а не плиометрическую.", cn: "增强式训练要质量胜于数量——高次数变成跳跃训练，而非增强式训练。", icon: "✨" },
    { en: "The stretch-shortening cycle produces a much more powerful contraction than concentric action alone.", ru: "Цикл растяжение-сокращение производит гораздо более мощное сокращение, чем только концентрическое действие.", cn: "拉伸-缩短周期产生的收缩力远大于单独的向心收缩。", icon: "🔋" },
    { en: "A well-developed posterior chain (glutes, hamstrings, lower back) is a prerequisite for a good vertical jump.", ru: "Развитая задняя цепь (ягодицы, бицепсы бедра, поясница) — обязательное условие хорошего вертикального прыжка.", cn: "发达的后链（臀部、腘绳肌、下背部）是良好垂直跳跃的前提条件。", icon: "🦵" },
    { en: "Sprinting is nature's ultimate posterior chain developer — no special equipment required.", ru: "Спринт — лучший природный способ развития задней цепи. Никакого специального оборудования не нужно.", cn: "冲刺是自然界最好的后链训练器——不需要特殊设备。", icon: "🏃‍♂️" },
    { en: "Eyes should never focus on the bar during the approach — focus on check marks and the standard to maintain the curve.", ru: "Глаза никогда не должны фокусироваться на планке во время разбега — смотри на контрольные отметки и стойку.", cn: "助跑时眼睛不应注视横杆——专注于标记点和立柱以保持弧线。", icon: "👁️" },
    { en: "Power = Force × Velocity. To jump higher, you must become both stronger AND faster.", ru: "Мощность = Сила × Скорость. Чтобы прыгать выше — нужно стать и сильнее, И быстрее.", cn: "功率 = 力 × 速度。要跳得更高，你必须变得更强壮且更快。", icon: "📐" },
    { en: "Technical training should be limited to 10–15 jumps per session — fatigue alters the dynamics of the jump.", ru: "Техническая тренировка: 10–15 прыжков за занятие — усталость меняет динамику прыжка.", cn: "技术训练应限制在每次10-15跳——疲劳会改变跳跃的动力学。", icon: "📊" },
    { en: "Ground contact for elite sprinters is less than 0.100 seconds — the faster you reverse, the higher you fly.", ru: "Контакт с землёй у элитных спринтеров — менее 0.100 секунды. Чем быстрее ты переключаешься — тем выше летишь.", cn: "精英短跑运动员的地面接触时间不到0.100秒——反转越快，飞得越高。", icon: "⏱️" },
];

/**
 * Get random motivational quotes
 * @param {string} lang - 'en' | 'ru' | 'cn'
 * @param {number} count - how many quotes to return
 * @returns {Array<{text: string, author: string}>}
 */
function getRandomQuotes(lang, count) {
    const shuffled = [...MOTIVATION_QUOTES].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count).map(q => ({
        text: q[lang] || q.en,
        author: q.author || ''
    }));
}

/**
 * Get random jump principles
 * @param {string} lang - 'en' | 'ru' | 'cn'
 * @param {number} count - how many principles to return
 * @returns {Array<{text: string, icon: string}>}
 */
function getRandomPrinciples(lang, count) {
    const shuffled = [...JUMP_PRINCIPLES].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count).map(p => ({
        text: p[lang] || p.en,
        icon: p.icon || '💡'
    }));
}

/**
 * Build motivational HTML block for PDFs
 * @param {string} lang - 'en' | 'ru' | 'cn'
 * @param {number} quoteCount - default 3
 * @param {number} principleCount - default 2
 * @returns {string} HTML string
 */
function buildMotivationBlock(lang) {
    const showQuote = Math.random() < 0.5;

    let html = `<div class="motivation-block">`;

    if (showQuote) {
        const q = getRandomQuotes(lang, 1)[0];
        html += `<div class="motivation-quote">`;
        html += `<span class="mq-text">"${q.text}"</span>`;
        if (q.author) html += `<span class="mq-author">— ${q.author}</span>`;
        html += `</div>`;
    } else {
        const p = getRandomPrinciples(lang, 1)[0];
        html += `<div class="motivation-principle">`;
        html += `<span class="mp-icon">${p.icon}</span>`;
        html += `<span class="mp-text">${p.text}</span>`;
        html += `</div>`;
    }

    html += `</div>`;
    return html;
}
